# version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/flashcard
      - LINE_CHANNEL_ACCESS_TOKEN=${LINE_CHANNEL_ACCESS_TOKEN}
    depends_on:
      - db
    volumes:
      - .:/app

  cloudflared:
    image: cloudflare/cloudflared:latest
    network_mode: "host"
    command: tunnel --no-autoupdate run --token ${CF_TUNNEL_TOKEN}
    restart: unless-stopped

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=flashcard
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - .:/app
    ports:
      - "5433:5432"

  cron:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "while true; do node src/main.js; sleep 240; done"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/flashcard
      - LINE_CHANNEL_ACCESS_TOKEN=${LINE_CHANNEL_ACCESS_TOKEN}
    depends_on:
      - db

  kanjicheck:
    build: .
    command: node src/kanji-check.js
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/flashcard
      - LINE_CHANNEL_ACCESS_TOKEN=${LINE_CHANNEL_ACCESS_TOKEN}
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data: